name: "Build & Test"

on:
  pull_request:
    branches:
      - main

jobs:
  build-ui:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.6-chrome100-ff98
    defaults:
      run:
        working-directory: ui
    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Build UI
        run: yarn run build

      - name: Run E2E Tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: ui
          install: false
          start: yarn run serve-build
          wait-on: "http://localhost:5000"
